# Generated by Django 3.2.5 on 2023-06-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='CNI',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='antecedent',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='domicile',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='group_sanguin',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='lieu_travail',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='telephone_lieu_travail',
        ),
        migrations.AddField(
            model_name='consultation',
            name='antecedents',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescriptions',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultation',
            name='remarque',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
