# Generated by Django 3.2.5 on 2023-06-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_auto_20230619_0813'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='schedule',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.schedule'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptomes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
