# Generated by Django 3.2.5 on 2023-06-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_auto_20230619_1412'),
        ('consultation', '0004_auto_20230619_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='remarque',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='schedule',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='utility.schedule'),
        ),
    ]
