# Generated by Django 3.2.5 on 2023-06-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_alter_consultation_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='medecin_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
