# Generated by Django 3.2.5 on 2023-03-14 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(default='')),
                ('type', models.CharField(choices=[('commune', 'commune'), ('Vip', 'Vip')], default='commune', max_length=8)),
                ('Nombre_lit', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('batiment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plateau_technique.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('est_libre', models.BooleanField(default=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('chambre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateau_technique.chambre')),
            ],
        ),
    ]
