# Generated by Django 4.1.2 on 2023-03-16 06:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("grh", "0001_initial"),
        ("plateau_technique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=225, unique=True)),
                (
                    "classe",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        default="C",
                        max_length=2,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/infrastructures"
                    ),
                ),
                ("localisation", models.CharField(max_length=50)),
                ("latitude", models.CharField(default="", max_length=50)),
                ("longitude", models.CharField(default="", max_length=50)),
                ("ville", models.CharField(max_length=30)),
                ("telephone", models.CharField(max_length=30)),
                ("fax", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
                ("site_web", models.URLField(blank=True, max_length=100, null=True)),
                ("date_creation", models.DateField()),
                ("date_enregistrement", models.DateTimeField(auto_now_add=True)),
                (
                    "directeur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grh.personnel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        default=None, null=True, upload_to="images/locaux/"
                    ),
                ),
                (
                    "supericie",
                    models.PositiveIntegerField(
                        blank=True, default=None, help_text="En mètres carré", null=True
                    ),
                ),
                ("localisation", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "batiment",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plateau_technique.batiment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(default="", max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="images/services"
                    ),
                ),
                (
                    "batiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plateau_technique.batiment",
                    ),
                ),
                (
                    "chef",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grh.personnel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materiel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        default=None, null=True, upload_to="images/materiels/"
                    ),
                ),
                ("numero_serie", models.CharField(default="", max_length=100)),
                ("date_arrivage", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Informatique", "Informatique"),
                            ("Medical", "Médical"),
                            ("Mobilier", "Mobilier"),
                            ("Electronique", "Electronique"),
                            ("Bureau", "Bureau"),
                        ],
                        default="Medical",
                        max_length=50,
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plateau_technique.local",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfrastructurePersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_embauche", models.DateField(default=None, null=True)),
                (
                    "infrastructure",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plateau_technique.infrastructure",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grh.personnel",
                    ),
                ),
            ],
        ),
    ]
