# Generated by Django 3.2.5 on 2023-06-19 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grh', '0003_auto_20230616_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('duree', models.DateField(blank=True, null=True)),
                ('date_fin', models.IntegerField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, default='', max_length=20)),
                ('guest', models.CharField(blank=True, default='', max_length=20)),
                ('statut', models.CharField(choices=[('Planned', 'Planned'), ('Not_Allocated', 'Not_Allocated'), ('Allocated', 'Allocated'), ('Running', 'Running'), ('Canceled', 'Canceled'), ('Terminated', 'Terminated')], default='Externe', max_length=20)),
                ('personnel', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grh.personnel')),
            ],
        ),
    ]
