# Generated by Django 3.2.5 on 2023-06-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='statut',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Not_Allocated', 'Not_Allocated'), ('Allocated', 'Allocated'), ('Running', 'Running'), ('Canceled', 'Canceled'), ('Terminated', 'Terminated')], default='Planned', max_length=20),
        ),
    ]
