# Generated by Django 3.2.5 on 2023-06-19 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0003_auto_20230616_1454'),
        ('utility', '0002_alter_schedule_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.TextField(default='Task')),
                ('personnel', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grh.personnel')),
            ],
        ),
    ]
