# Generated by Django 3.2.5 on 2023-06-14 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretaire', '0004_alter_patient_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('designation', models.CharField(max_length=15)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaire.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LigneExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prélevement', models.CharField(max_length=15)),
                ('paramètre', models.CharField(max_length=15)),
                ('val_trouvée', models.CharField(max_length=15)),
                ('observation', models.CharField(max_length=50)),
                ('examen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.examen')),
            ],
        ),
    ]
