# Generated by Django 5.0 on 2024-01-24 20:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCathegorie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChambreInternement',
            fields=[
                ('numeroChambre', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
                ('standard', models.CharField(choices=[('0', 'Classique'), ('1', 'VIP'), ('2', 'Prestige'), ('3', 'Gold')], max_length=1, validators=[django.core.validators.RegexValidator('^[0-3]$', 'La catégorie doit être comprise entre 0 et 3.')])),
                ('capacite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('description', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('type', models.CharField(max_length=20)),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('commentaires', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=20)),
                ('type', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('somme', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('destination', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Impot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('porcentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('nom', models.CharField(max_length=20)),
                ('tel', models.IntegerField(validators=[django.core.validators.MinValueValidator(600000000), django.core.validators.MaxValueValidator(699999999)])),
                ('cni', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=160)),
                ('adresse', models.CharField(max_length=100)),
                ('commentaire', models.CharField(max_length=100)),
                ('salaireDeBase', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('particularite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=20)),
                ('matriculeObjetStocke', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('datePeremption', models.DateField()),
                ('commentaire', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('matriculeObjetDeplace', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('magasinDeDepart', models.CharField(max_length=20)),
                ('magasinArrivee', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
                ('commentaire', models.CharField(max_length=100)),
                ('matriculeDepense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.depense')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueImpotPaye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('idImpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.impot')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('idMedicament', models.AutoField(default='0', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('prixUnitaireDeVente', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('idCategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.categoriemedicament')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.CharField(max_length=10000)),
                ('datePeremption', models.DateField()),
                ('commentaire', models.CharField(max_length=100)),
                ('nomMedicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOperation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.operation')),
                ('matriculeMedecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('pourcentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('matriculeInvestisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Internement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroLit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('commentaire', models.CharField(max_length=1000)),
                ('numeroChambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.chambreinternement')),
                ('matriculePatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.personne')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePaiementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sommePercue', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
                ('date', models.DateField()),
                ('matriculeEmploye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.personne')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueOpererationEffectue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('idOperation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.operation')),
                ('matriculePatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.personne')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueExamenEffectue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDepot', models.DateField()),
                ('dateRetrait', models.DateField()),
                ('resultat', models.CharField(max_length=100)),
                ('idExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.examen')),
                ('matriculePatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.personne')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostique', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('MatriculeConsultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.consultation')),
                ('matriculeMedecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculeMedecinHistoriqueConsultation', to='comptabilite.personne')),
                ('matriculePatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculePatientHistoriqueConsultation', to='comptabilite.personne')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('matriculeObjetAchete', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('idCaisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.caisse')),
                ('matriculeCaissiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.personne')),
            ],
        ),
        migrations.CreateModel(
            name='DonPersonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.don')),
                ('matriculeDonateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreActions', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('dateDebut', models.DateField()),
                ('matriculeActionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.personne')),
            ],
        ),
        migrations.AddField(
            model_name='personne',
            name='idPoste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.poste'),
        ),
        migrations.CreateModel(
            name='PrimeEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('commentaire', models.CharField(max_length=20)),
                ('idPrime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.prime')),
                ('matriculeEmploye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=500)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('date', models.DateField()),
                ('prixTotal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('type_Achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.typeachat')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('idTypeMateriel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.typemateriel')),
            ],
        ),
    ]
