# Generated by Django 5.0 on 2024-01-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObjetMedical',
            new_name='ObjetMedicaux',
        ),
        migrations.RemoveField(
            model_name='action',
            name='id',
        ),
        migrations.AlterField(
            model_name='action',
            name='matriculeActionnaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='comptabilite.actionnaire'),
        ),
    ]
