# Generated by Django 5.0 on 2024-01-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambreinternement',
            old_name='prix',
            new_name='prixDuLit',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='type',
            new_name='NomConsultation',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='idMedicament',
            new_name='MatriculeMedicament',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='motif',
            new_name='nomProduit',
        ),
        migrations.RemoveField(
            model_name='chambreinternement',
            name='service',
        ),
        migrations.AlterField(
            model_name='categoriemedicament',
            name='nomCathegorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poste',
            name='particularite',
            field=models.CharField(max_length=100),
        ),
    ]
