# Generated by Django 5.0 on 2024-01-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='categorieExamen',
        ),
        migrations.DeleteModel(
            name='TypeExamen',
        ),
    ]
