# Generated by Django 5.0 on 2024-01-25 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_remove_examen_categorieexamen_delete_typeexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExamen',
            fields=[
                ('idTypeExamen', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='categorieExamen',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='comptabilite.typeexamen'),
            preserve_default=False,
        ),
    ]
