# Generated by Django 5.0 on 2024-01-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_rename_objetmedical_objetmedicaux_remove_action_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorieObjetMedical',
            new_name='CategorieObjetMedicaux',
        ),
    ]
