# Generated by Django 5.0 on 2024-01-24 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_remove_don_type_don_typededon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impot',
            name='porcentage',
        ),
        migrations.AddField(
            model_name='impot',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='don',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
