# Generated by Django 5.0 on 2024-01-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_remove_impot_porcentage_impot_pourcentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prime',
            name='type',
        ),
        migrations.AddField(
            model_name='prime',
            name='Nom',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poste',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prime',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
