# Generated by Django 5.0 on 2024-01-24 23:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_remove_prime_type_prime_nom_alter_poste_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='idPoste',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='salaireDeBase',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='commentaire',
        ),
        migrations.CreateModel(
            name='employée',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comptabilite.personne')),
                ('salaireDeBase', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
                ('idPoste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.poste')),
            ],
            bases=('comptabilite.personne',),
        ),
    ]
