# Generated by Django 5.0 on 2024-01-24 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_remove_personne_idposte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='actionnaire',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='comptabilite.personne')),
                ('idactionnaire', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('comptabilite.personne',),
        ),
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='comptabilite.personne')),
                ('idfournisseur', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('comptabilite.personne',),
        ),
        migrations.CreateModel(
            name='investisseur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='comptabilite.personne')),
                ('idInvestisseur', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('comptabilite.personne',),
        ),
    ]
