# Generated by Django 5.0 on 2024-01-25 00:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_actionnaire_fournisseur_investisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donnateur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comptabilite.personne')),
                ('nombreTotalDeDonnation', models.IntegerField(default=0)),
            ],
            bases=('comptabilite.personne',),
        ),
        migrations.RemoveField(
            model_name='actionnaire',
            name='idactionnaire',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='idfournisseur',
        ),
        migrations.RemoveField(
            model_name='investisseur',
            name='idInvestisseur',
        ),
        migrations.AddField(
            model_name='actionnaire',
            name='nombreTotal_d_action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='adresse_entreprise',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='entreprise',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='numero_siret_entreprise',
            field=models.CharField(default='none', max_length=14),
        ),
        migrations.AddField(
            model_name='investisseur',
            name='nombreSessionCourante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investisseur',
            name='nombreTotal_d_investissement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='matriculeActionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.actionnaire'),
        ),
        migrations.AlterField(
            model_name='actionnaire',
            name='personne_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comptabilite.personne'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='matricule',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^.{8}$')]),
        ),
        migrations.AlterField(
            model_name='depense',
            name='matricule',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^.{8}$')]),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='personne_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comptabilite.personne'),
        ),
        migrations.AlterField(
            model_name='historiquepaiementsalaire',
            name='matriculeEmploye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.employée'),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='matriculeInvestisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.investisseur'),
        ),
        migrations.AlterField(
            model_name='investisseur',
            name='personne_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comptabilite.personne'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='matricule',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^.{8}$', 'Le champ doit contenir exactement 6 caractères.')]),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='donpersonne',
            name='matriculeDonateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.donnateur'),
        ),
    ]
