# Generated by Django 5.0 on 2024-01-25 01:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0008_donnateur_remove_actionnaire_idactionnaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieObjetMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCategorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comptabilite.personne')),
                ('specificité', models.CharField(max_length=200, null=True)),
            ],
            bases=('comptabilite.personne',),
        ),
        migrations.CreateModel(
            name='TypeConsultation',
            fields=[
                ('matricule', models.AutoField(primary_key=True, serialize=False)),
                ('NomConsultation', models.CharField(max_length=20)),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('commentaires', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='categoriemedicament',
            old_name='nomCathegorie',
            new_name='nomCategorie',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='MatriculeMedicament',
        ),
        migrations.AddField(
            model_name='historiqueconsultation',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historiqueconsultation',
            name='descriptionSymptom',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historiqueconsultation',
            name='poid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='matricule',
            field=models.CharField(default=0, max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^.{8}$', 'Le champ doit contenir exactement 8 caractères.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personne',
            name='matricule',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^.{8}$', 'Le champ doit contenir exactement 8 caractères.')]),
        ),
        migrations.AlterField(
            model_name='primeemploye',
            name='matriculeEmploye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.employée'),
        ),
        migrations.CreateModel(
            name='ObjetMedical',
            fields=[
                ('matricule', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^.{8}$', 'Le champ doit contenir exactement 8 caractères.')])),
                ('nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('prixUnitaireDeVente', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('idCategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.categorieobjetmedical')),
            ],
        ),
        migrations.AlterField(
            model_name='historiqueconsultation',
            name='matriculePatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculePatientHistoriqueConsultation', to='comptabilite.patient'),
        ),
        migrations.AlterField(
            model_name='historiqueconsultation',
            name='MatriculeConsultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.typeconsultation'),
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
