# Generated by Django 5.0 on 2024-01-25 02:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0009_categorieobjetmedical_patient_typeconsultation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventaireStock',
            fields=[
                ('nomProduit', models.CharField(max_length=200)),
                ('matriculeObjetStocke', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^.{8}$')])),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('datePeremption', models.DateField()),
                ('commentaire', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='magasin',
            fields=[
                ('idMagasin', models.IntegerField(primary_key=True, serialize=False)),
                ('localisation', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Depense',
            new_name='TypeDepense',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='historiquecaisse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='participationoperation',
            name='matriculeMedecin',
        ),
        migrations.RemoveField(
            model_name='transactionmagasin',
            name='id',
        ),
        migrations.AddField(
            model_name='achat',
            name='nomProduit',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiqueopererationeffectue',
            name='resultat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participationoperation',
            name='matriculeEmployé',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='comptabilite.employée'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiquecaisse',
            name='matriculeCaissiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.employée'),
        ),
        migrations.AlterField(
            model_name='historiquecaisse',
            name='matriculeObjetAchete',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^.{8}$')]),
        ),
        migrations.AlterField(
            model_name='historiqueconsultation',
            name='descriptionSymptom',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiqueexameneffectue',
            name='matriculePatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.patient'),
        ),
        migrations.AlterField(
            model_name='historiqueopererationeffectue',
            name='matriculePatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.patient'),
        ),
        migrations.AlterField(
            model_name='internement',
            name='matriculePatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.patient'),
        ),
        migrations.AlterField(
            model_name='transactionmagasin',
            name='matriculeObjetDeplace',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^.{8}$')]),
        ),
        migrations.AlterField(
            model_name='typemateriel',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='inventairestock',
            name='idMagasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.magasin'),
        ),
    ]
