# Generated by Django 5.0 on 2024-01-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0010_inventairestock_magasin_rename_depense_typedepense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='motif',
        ),
    ]
