# Generated by Django 5.0 on 2024-01-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0011_remove_achat_motif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achat',
            old_name='nomProduit',
            new_name='motif',
        ),
    ]
