# Generated by Django 5.0 on 2024-01-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0012_rename_nomproduit_achat_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='nomProduit',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='specificité',
            field=models.CharField(blank=True, default=0, max_length=200),
            preserve_default=False,
        ),
    ]
