# Generated by Django 3.2.5 on 2023-06-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='matricule',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='CNI',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='domicile',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='group_sanguin',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='lieu_travail',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='telephone_lieu_travail',
        ),
        migrations.AddField(
            model_name='medicament',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='medicament',
            name='maladies',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='medicament',
            name='nom_court',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicament',
            name='notice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='prix',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='medicament',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='restrictions',
            field=models.CharField(choices=[('A', 'Aucunes'), ('FA', 'Femmes Enceintes'), ('ENFANTS', 'Enfants (-12 ans)')], default='A', max_length=8),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='statut',
            field=models.CharField(choices=[('OutOfStock', 'OutOfStock'), ('Available', 'Available')], default='Available', max_length=10),
        ),
    ]
