# Generated by Django 3.2.5 on 2023-03-16 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretaire', '0003_alter_patient_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prestation', models.CharField(choices=[('Q-CONSULT_spécialiste', 'Consultation médecin specialiste'), ('Q-CONSULT_généraliste', 'Consultation médecin généraliste'), ('Q-RENDEZ-VOUS_spécialiste', 'rendez-vous médecin specialiste'), ('Q-RENDEZ-VOUS_généraliste', 'rendez-vous médecin généraliste'), ('Q-EXAM', 'Examen')], max_length=40)),
                ('montant_TTC', models.PositiveIntegerField()),
                ('est_paye', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaire.patient')),
            ],
        ),
    ]
