# Generated by Django 3.2.5 on 2023-06-20 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0009_auto_20230616_1606'),
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('montant', models.IntegerField()),
                ('type', models.BooleanField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Service', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('montant', models.IntegerField()),
                ('statut', models.BooleanField(choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], default='UnPaid', max_length=8)),
                ('elements', models.ManyToManyField(blank=True, to='caisse.BillElement')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaire.patient')),
            ],
        ),
    ]
