# Generated by Django 3.2.5 on 2023-03-11 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('CNI', models.CharField(default='', max_length=20)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(default='', max_length=20)),
                ('telephone', models.CharField(default='', max_length=15)),
                ('nationalite', models.CharField(default='Camerounais', max_length=50)),
                ('profession', models.CharField(default='Eleve', max_length=50)),
                ('lieu_travail', models.CharField(default='', max_length=50)),
                ('telephone_lieu_travail', models.CharField(default='', max_length=15)),
                ('domicile', models.CharField(default='', max_length=20)),
                ('group_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=10)),
                ('statut', models.CharField(choices=[('Externe', 'Externe'), ('Interne', 'Interne')], default='Externe', max_length=8)),
                ('antecedent', models.TextField(default='')),
            ],
        ),
    ]
