# Generated by Django 3.2.5 on 2023-03-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateau_technique', '0001_initial'),
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_internement', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(default=None, null=True)),
                ('en_cours', models.BooleanField(default=True)),
                ('lit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateau_technique.lit')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaire.patient')),
            ],
        ),
    ]
