# Generated by Django 3.2.5 on 2023-03-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0002_internement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='matricule',
            field=models.CharField(max_length=20),
        ),
    ]
