# Generated by Django 3.2.5 on 2023-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0003_alter_patient_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
