# Generated by Django 3.2.5 on 2023-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0004_alter_patient_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='H', max_length=1),
        ),
    ]
