# Generated by Django 3.2.5 on 2023-06-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0006_auto_20230616_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='matricule',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
