# Generated by Django 3.2.5 on 2023-06-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0007_alter_patient_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='domicile',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lieu_travail',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone_lieu_travail',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
