# Generated by Django 3.2.5 on 2023-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0008_auto_20230616_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='domicile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lieu_travail',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone_lieu_travail',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
