# Generated by Django 3.2.5 on 2023-06-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0009_auto_20230616_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
