# Generated by Django 4.1.2 on 2023-03-16 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_personnel",
                    models.CharField(
                        choices=[
                            ("Medecin", "Médecin"),
                            ("Caissier", "Caissier"),
                            ("Secretaire", "Sécrétaire"),
                            ("Infirmer", "Infirmier"),
                            ("Laborantin", "Laborantin"),
                            ("Stagiaire", "Stagiaire"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        default=None, null=True, upload_to="images/personnels/"
                    ),
                ),
                ("prenom", models.CharField(max_length=50)),
                ("matricule", models.CharField(max_length=20, unique=True)),
                (
                    "etat_civil",
                    models.CharField(
                        choices=[("MR", "M."), ("MME", "Mme."), ("MLLE", "Mlle.")],
                        default="MR",
                        max_length=5,
                    ),
                ),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(max_length=50)),
                ("nationalite", models.CharField(max_length=50)),
                ("domicile", models.CharField(max_length=50)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=50)),
                ("telephone", models.CharField(default="", max_length=15)),
                ("CNI", models.CharField(max_length=50, unique=True)),
                ("should_update_password", models.BooleanField(default=True)),
                (
                    "poste",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grh.poste",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
