# Generated by Django 4.1.2 on 2023-03-25 10:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("grh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caissier",
            fields=[
                (
                    "personnel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="grh.personnel",
                    ),
                ),
            ],
            bases=("grh.personnel",),
        ),
        migrations.CreateModel(
            name="Infirmier",
            fields=[
                (
                    "personnel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="grh.personnel",
                    ),
                ),
            ],
            bases=("grh.personnel",),
        ),
        migrations.CreateModel(
            name="Laborantin",
            fields=[
                (
                    "personnel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="grh.personnel",
                    ),
                ),
            ],
            bases=("grh.personnel",),
        ),
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "personnel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="grh.personnel",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("G", "Généraliste"), ("S", "Spécialiste")],
                        default="G",
                        max_length=5,
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
            ],
            bases=("grh.personnel",),
        ),
        migrations.CreateModel(
            name="Secretaire",
            fields=[
                (
                    "personnel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="grh.personnel",
                    ),
                ),
            ],
            bases=("grh.personnel",),
        ),
        migrations.CreateModel(
            name="Remuneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("montant", models.PositiveIntegerField()),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grh.personnel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilSpecialiste",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("specialite", models.CharField(max_length=50)),
                ("date_obtention", models.DateField(default=None, null=True)),
                (
                    "medecin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="grh.medecin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_heure", models.DateTimeField(auto_now_add=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grh.personnel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_prise_permission", models.DateField()),
                ("date_retour", models.DateField(blank=True)),
                ("duree", models.DurationField()),
                ("justificatif", models.TextField()),
                ("date_creation", models.DateField(auto_now_add=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grh.personnel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Periode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequence",
                    models.CharField(
                        choices=[("repeat", "Répété"), ("fixed", "Fixé")],
                        default="repeat",
                        max_length=15,
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("en_service", models.BooleanField(default=True)),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "lundi"),
                            (1, "mardi"),
                            (2, "mercredi"),
                            (3, "jeudi"),
                            (4, "vendredi"),
                            (5, "samedi"),
                            (6, "dimanche"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("description", models.TextField(default="")),
                ("sujet", models.CharField(default="Consultation", max_length=100)),
                ("localisation", models.CharField(default="", max_length=100)),
                (
                    "personnel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grh.personnel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_heure", models.DateTimeField()),
                ("justificatif", models.TextField(blank=True, default="")),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grh.personnel"
                    ),
                ),
            ],
        ),
    ]
