# Generated by Django 3.2.5 on 2023-06-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0002_caissier_infirmier_laborantin_medecin_secretaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='CNI',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='domicile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='lieu_naissance',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nationalite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type_personnel',
            field=models.CharField(choices=[('Medecin', 'Médecin'), ('Caissier', 'Caissier'), ('Secretaire', 'Sécrétaire'), ('Infirmer', 'Infirmier'), ('Laborantin', 'Laborantin'), ('Stagiaire', 'Stagiaire'), ('Plateau', 'Plateau')], default='', max_length=20),
        ),
    ]
